/**
 * Visual dashboard component registry.
 * The schema is inspired by BI tools such as Redash/DataEase:
 * each visual has display metadata, default config, editable fields, and mock data.
 */

export const CHART_CATEGORIES = [
  {
    label: '图表',
    key: 'chart',
    nodes: ['bar', 'line', 'pie', 'scatter', 'area', 'radar', 'funnel', 'gauge', 'wordCloud', 'liquidFill'],
  },
  {
    label: '指标与文本',
    key: 'metric',
    nodes: ['numberCounter', 'table', 'titleText', 'richText', 'dateTime'],
  },
  {
    label: '媒体与装饰',
    key: 'decoration',
    nodes: ['image', 'video', 'borderBox', 'decoration', 'background'],
  },
]

const DEFAULT_DATA_SOURCE = {
  type: 'mock',
  datasetId: '',
  queryName: '',
  sql: '',
  apiUrl: '',
  apiMethod: 'GET',
  apiHeaders: '',
  requestBody: '',
  apiDataPath: '',
  refreshInterval: 0,
  lastRefreshTime: null,
  fieldMapping: '',
}

const COMMON_CHART_FIELDS = [
  { key: 'showLegend', label: '显示图例', type: 'switch' },
  { key: 'showTooltip', label: '显示提示框', type: 'switch' },
  { key: 'showLabel', label: '显示数值标签', type: 'switch' },
  { key: 'theme', label: '配色主题', type: 'select', options: ['default', 'dark', 'vintage', 'macarons', 'shine'] },
]

export const CHART_TYPE_CONFIG = {
  bar: {
    type: 'bar',
    label: '柱状图',
    icon: '▥',
    color: '#2563eb',
    category: 'chart',
    description: '对比分类维度下的指标数值',
    defaultSize: { w: 520, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '区域销售额对比',
      xField: '华东,华南,华北,西南,西北,华中',
      yField: '128,96,86,72,58,66',
      seriesName: '销售额(万元)',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      theme: 'default',
      barWidth: 'auto',
      horizontal: false,
      colors: ['#2563eb', '#14b8a6', '#f59e0b', '#ef4444'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text', placeholder: '输入标题' },
      { key: 'xField', label: '分类轴数据', type: 'textarea', placeholder: '用逗号分隔，如 华东,华南,华北' },
      { key: 'yField', label: '数值轴数据', type: 'textarea', placeholder: '用逗号分隔，如 120,200,150' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'horizontal', label: '横向柱状图', type: 'switch' },
      { key: 'barWidth', label: '柱宽', type: 'text', placeholder: 'auto 或数字(px)' },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '区域销售额对比',
      xField: '华东,华南,华北,西南,西北,华中',
      yField: '128,96,86,72,58,66',
      seriesName: '销售额(万元)',
    }),
  },

  line: {
    type: 'line',
    label: '折线图',
    icon: '⌁',
    color: '#16a34a',
    category: 'chart',
    description: '展示指标随时间变化的趋势',
    defaultSize: { w: 560, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '近 12 月营收趋势',
      xField: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
      yField: '120,132,145,168,182,210,225,248,260,278,295,320',
      seriesName: '营收(万元)',
      smooth: true,
      showArea: true,
      showLegend: false,
      showTooltip: true,
      showLabel: false,
      theme: 'default',
      colors: ['#14b8a6'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'xField', label: 'X 轴数据', type: 'textarea' },
      { key: 'yField', label: 'Y 轴数据', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'smooth', label: '平滑曲线', type: 'switch' },
      { key: 'showArea', label: '显示面积', type: 'switch' },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '近 12 月营收趋势',
      xField: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
      yField: '120,132,145,168,182,210,225,248,260,278,295,320',
      seriesName: '营收(万元)',
    }),
  },

  area: {
    type: 'area',
    label: '面积图',
    icon: '▰',
    color: '#0891b2',
    category: 'chart',
    description: '强调趋势累计量和变化幅度',
    defaultSize: { w: 560, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '季度增长面积图',
      xField: 'Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4',
      yField: '280,350,420,510,560,620,710,850',
      seriesName: '收入(万元)',
      smooth: true,
      showLegend: false,
      showTooltip: true,
      showLabel: false,
      theme: 'default',
      colors: ['#0891b2'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'xField', label: 'X 轴数据', type: 'textarea' },
      { key: 'yField', label: 'Y 轴数据', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'smooth', label: '平滑曲线', type: 'switch' },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '季度增长面积图',
      xField: 'Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4',
      yField: '280,350,420,510,560,620,710,850',
      seriesName: '收入(万元)',
    }),
  },

  pie: {
    type: 'pie',
    label: '饼图',
    icon: '◔',
    color: '#f59e0b',
    category: 'chart',
    description: '展示部分占整体的比例',
    defaultSize: { w: 420, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '渠道贡献占比',
      dataLabels: '自然流量,广告投放,渠道合作,老客复购,活动引流',
      dataValues: '335,310,234,180,148',
      seriesName: '渠道',
      radius: '60%',
      roseType: false,
      showLegend: true,
      showTooltip: true,
      showLabel: true,
      theme: 'default',
      colors: ['#2563eb', '#14b8a6', '#f59e0b', '#ef4444', '#8b5cf6'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'dataLabels', label: '数据标签', type: 'textarea' },
      { key: 'dataValues', label: '数据值', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'radius', label: '半径', type: 'text', placeholder: '如 60%' },
      { key: 'roseType', label: '玫瑰图', type: 'switch' },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '渠道贡献占比',
      dataLabels: '自然流量,广告投放,渠道合作,老客复购,活动引流',
      dataValues: '335,310,234,180,148',
      seriesName: '渠道',
    }),
  },

  scatter: {
    type: 'scatter',
    label: '散点图',
    icon: '∴',
    color: '#ef4444',
    category: 'chart',
    description: '分析两个指标之间的相关性',
    defaultSize: { w: 520, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '投放成本 vs 销售额',
      xField: '12,23,35,42,55,63,78,85,92,105,118,130',
      yField: '18,35,52,68,82,95,110,128,140,158,172,195',
      seriesName: '城市样本',
      symbolSize: 12,
      showLegend: false,
      showTooltip: true,
      theme: 'default',
      colors: ['#ef4444'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'xField', label: 'X 轴数据', type: 'textarea' },
      { key: 'yField', label: 'Y 轴数据', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'symbolSize', label: '点大小', type: 'number' },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '投放成本 vs 销售额',
      xField: '12,23,35,42,55,63,78,85,92,105,118,130',
      yField: '18,35,52,68,82,95,110,128,140,158,172,195',
      seriesName: '城市样本',
    }),
  },

  radar: {
    type: 'radar',
    label: '雷达图',
    icon: '◎',
    color: '#fb7185',
    category: 'chart',
    description: '多维指标综合对比',
    defaultSize: { w: 420, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '城市综合指标',
      indicators: '经济发展,民生保障,科技创新,生态环境,交通出行,公共安全',
      dataValues: '92,85,78,88,80,90',
      seriesName: '本年度',
      shape: 'polygon',
      showLegend: false,
      showTooltip: true,
      theme: 'default',
      colors: ['#fb7185'],
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'indicators', label: '维度指标', type: 'textarea' },
      { key: 'dataValues', label: '指标值', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'shape', label: '形状', type: 'select', options: ['polygon', 'circle'] },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '城市综合指标',
      indicators: '经济发展,民生保障,科技创新,生态环境,交通出行,公共安全',
      dataValues: '92,85,78,88,80,90',
      seriesName: '本年度',
    }),
  },

  funnel: {
    type: 'funnel',
    label: '漏斗图',
    icon: '▽',
    color: '#22c55e',
    category: 'chart',
    description: '展示业务环节的转化漏斗',
    defaultSize: { w: 420, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '用户转化漏斗',
      stages: '访问页面,查看商品,加入购物车,提交订单,支付成功',
      values: '12000,8200,4300,2600,2100',
      seriesName: '转化',
      sort: 'descending',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      theme: 'default',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'stages', label: '阶段名称', type: 'textarea' },
      { key: 'values', label: '阶段数值', type: 'textarea' },
      { key: 'seriesName', label: '系列名称', type: 'text' },
      { key: 'sort', label: '排序方式', type: 'select', options: ['descending', 'ascending'] },
      ...COMMON_CHART_FIELDS,
    ],
    mockData: () => ({
      title: '用户转化漏斗',
      stages: '访问页面,查看商品,加入购物车,提交订单,支付成功',
      values: '12000,8200,4300,2600,2100',
    }),
  },

  gauge: {
    type: 'gauge',
    label: '仪表盘',
    icon: '◉',
    color: '#dc2626',
    category: 'chart',
    description: '展示单一指标的进度或状态',
    defaultSize: { w: 320, h: 280 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '年度 KPI 完成率',
      value: 85,
      min: 0,
      max: 100,
      unit: '%',
      seriesName: 'KPI',
      theme: 'default',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'value', label: '当前值', type: 'number' },
      { key: 'min', label: '最小值', type: 'number' },
      { key: 'max', label: '最大值', type: 'number' },
      { key: 'unit', label: '单位', type: 'text' },
      { key: 'seriesName', label: '指标名称', type: 'text' },
    ],
    mockData: () => ({ title: '年度 KPI 完成率', value: 85 }),
  },

  wordCloud: {
    type: 'wordCloud',
    label: '词云',
    icon: '☁',
    color: '#8b5cf6',
    category: 'chart',
    description: '展示文本关键词的热度分布',
    defaultSize: { w: 500, h: 330 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '热门业务主题',
      words: '人工智能:100,大数据:95,实时计算:88,湖仓一体:82,数据治理:78,指标平台:72,可视化:65,数据质量:58,数据血缘:48',
      shape: 'circle',
      theme: 'default',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'words', label: '词汇与权重', type: 'textarea', placeholder: '格式：词:权重，用逗号分隔' },
      { key: 'shape', label: '形状', type: 'select', options: ['circle', 'cardioid', 'diamond', 'triangle', 'star'] },
    ],
    mockData: () => ({
      title: '热门业务主题',
      words: '人工智能:100,大数据:95,实时计算:88,湖仓一体:82,数据治理:78,指标平台:72,可视化:65,数据质量:58,数据血缘:48',
    }),
  },

  liquidFill: {
    type: 'liquidFill',
    label: '水位图',
    icon: '◌',
    color: '#06b6d4',
    category: 'chart',
    description: '用水位动效展示百分比进度',
    defaultSize: { w: 280, h: 280 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '项目进度',
      value: 68,
      unit: '%',
      waveColor: '#06b6d4',
      seriesName: '完成进度',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'value', label: '百分比', type: 'slider', min: 0, max: 100, step: 1 },
      { key: 'unit', label: '单位', type: 'text' },
      { key: 'waveColor', label: '水位颜色', type: 'text', placeholder: '#06b6d4' },
      { key: 'seriesName', label: '指标名称', type: 'text' },
    ],
    mockData: () => ({ title: '项目进度', value: 68 }),
  },

  numberCounter: {
    type: 'numberCounter',
    label: '指标卡',
    icon: '#',
    color: '#f59e0b',
    category: 'metric',
    description: '展示关键业务指标和单位',
    defaultSize: { w: 260, h: 140 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.78)', border: '1px solid rgba(148,163,184,0.2)', boxShadow: '0 10px 28px rgba(0,0,0,0.24)' },
    defaultConfig: {
      title: '累计用户数',
      value: 1284567,
      prefix: '',
      suffix: ' 人',
      fontSize: 42,
      color: '#38bdf8',
      duration: 1200,
      separator: ',',
      trend: '+12.8%',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'value', label: '数值', type: 'number' },
      { key: 'prefix', label: '前缀', type: 'text' },
      { key: 'suffix', label: '后缀', type: 'text' },
      { key: 'trend', label: '趋势文本', type: 'text' },
      { key: 'fontSize', label: '数字大小', type: 'number' },
      { key: 'color', label: '数字颜色', type: 'text' },
      { key: 'separator', label: '分隔符', type: 'text' },
    ],
    mockData: () => ({ title: '累计用户数', value: 1284567, trend: '+12.8%' }),
  },

  titleText: {
    type: 'titleText',
    label: '标题文本',
    icon: 'T',
    color: '#334155',
    category: 'metric',
    description: '大屏标题、副标题或分组标题',
    defaultSize: { w: 560, h: 80 },
    defaultStyle: { opacity: 1, borderRadius: 0, background: 'transparent', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      text: '数据运营指挥中心',
      fontSize: 36,
      fontWeight: '700',
      color: '#ffffff',
      textAlign: 'center',
      textShadow: '0 2px 18px rgba(37,99,235,0.45)',
      letterSpacing: 0,
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'text', label: '文本内容', type: 'text' },
      { key: 'fontSize', label: '字体大小', type: 'number' },
      { key: 'fontWeight', label: '字重', type: 'select', options: ['400', '500', '600', '700', '800', '900'] },
      { key: 'color', label: '字体颜色', type: 'text' },
      { key: 'textAlign', label: '对齐方式', type: 'select', options: ['left', 'center', 'right'] },
      { key: 'letterSpacing', label: '字间距(px)', type: 'number' },
      { key: 'textShadow', label: '文字阴影', type: 'text' },
    ],
    mockData: () => ({ text: '数据运营指挥中心' }),
  },

  richText: {
    type: 'richText',
    label: '说明文本',
    icon: '¶',
    color: '#475569',
    category: 'metric',
    description: '展示分析结论、说明或公告',
    defaultSize: { w: 420, h: 200 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      content: '本看板聚合实时交易、履约、转化与质量指标，用于业务例会和大屏展示。',
      fontSize: 14,
      color: '#cbd5e1',
      lineHeight: 1.8,
      padding: '16px',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'content', label: '文本内容', type: 'textarea' },
      { key: 'fontSize', label: '字体大小', type: 'number' },
      { key: 'color', label: '文字颜色', type: 'text' },
      { key: 'lineHeight', label: '行高', type: 'number' },
      { key: 'padding', label: '内边距', type: 'text' },
    ],
    mockData: () => ({ content: '本看板聚合实时交易、履约、转化与质量指标，用于业务例会和大屏展示。' }),
  },

  dateTime: {
    type: 'dateTime',
    label: '日期时间',
    icon: '◷',
    color: '#64748b',
    category: 'metric',
    description: '实时显示当前日期和时间',
    defaultSize: { w: 300, h: 100 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      showTime: true,
      showDate: true,
      showWeek: true,
      fontSize: 28,
      color: '#ffffff',
      textAlign: 'center',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'showTime', label: '显示时间', type: 'switch' },
      { key: 'showDate', label: '显示日期', type: 'switch' },
      { key: 'showWeek', label: '显示星期', type: 'switch' },
      { key: 'fontSize', label: '字体大小', type: 'number' },
      { key: 'color', label: '字体颜色', type: 'text' },
      { key: 'textAlign', label: '对齐方式', type: 'select', options: ['left', 'center', 'right'] },
    ],
    mockData: () => ({}),
  },

  table: {
    type: 'table',
    label: '明细表',
    icon: '▤',
    color: '#3b82f6',
    category: 'metric',
    description: '展示结构化明细数据',
    defaultSize: { w: 560, h: 340 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.62)', border: '1px solid rgba(148,163,184,0.18)', boxShadow: 'none' },
    defaultConfig: {
      title: '销售排行 Top 10',
      columns: '排名,产品名称,销售额(万),增长率,负责人',
      rows: '1,智能终端X9,1280,+28.5%,张明\n2,云平台Pro,1150,+22.1%,李华\n3,数据引擎V3,980,+18.3%,王芳\n4,安全网关S5,865,+15.8%,赵磊\n5,AI分析套件,780,+32.6%,陈静',
      headerBg: 'rgba(37,99,235,0.32)',
      rowBg: 'transparent',
      stripeBg: 'rgba(255,255,255,0.035)',
      textColor: '#e2e8f0',
      fontSize: 13,
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '表格标题', type: 'text' },
      { key: 'columns', label: '列名', type: 'textarea' },
      { key: 'rows', label: '数据行', type: 'textarea' },
      { key: 'headerBg', label: '表头背景', type: 'text' },
      { key: 'textColor', label: '文字颜色', type: 'text' },
      { key: 'fontSize', label: '字体大小', type: 'number' },
    ],
    mockData: () => ({
      title: '销售排行 Top 10',
      columns: '排名,产品名称,销售额(万),增长率,负责人',
      rows: '1,智能终端X9,1280,+28.5%,张明\n2,云平台Pro,1150,+22.1%,李华\n3,数据引擎V3,980,+18.3%,王芳\n4,安全网关S5,865,+15.8%,赵磊\n5,AI分析套件,780,+32.6%,陈静',
    }),
  },

  image: {
    type: 'image',
    label: '图片',
    icon: '▧',
    color: '#8b5cf6',
    category: 'decoration',
    description: '展示静态图片资源',
    defaultSize: { w: 320, h: 200 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'transparent', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      src: '',
      alt: '图片',
      objectFit: 'cover',
      fallback: 'https://placehold.co/400x300/0f172a/94a3b8?text=Image',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'src', label: '图片地址', type: 'text' },
      { key: 'alt', label: '替代文本', type: 'text' },
      { key: 'objectFit', label: '填充方式', type: 'select', options: ['cover', 'contain', 'fill', 'none'] },
    ],
    mockData: () => ({}),
  },

  video: {
    type: 'video',
    label: '视频',
    icon: '▶',
    color: '#ef4444',
    category: 'decoration',
    description: '嵌入视频播放',
    defaultSize: { w: 520, h: 320 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: '#000000', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      src: '',
      autoplay: true,
      loop: true,
      muted: true,
      controls: false,
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'src', label: '视频地址', type: 'text' },
      { key: 'autoplay', label: '自动播放', type: 'switch' },
      { key: 'loop', label: '循环播放', type: 'switch' },
      { key: 'muted', label: '静音', type: 'switch' },
      { key: 'controls', label: '显示控制条', type: 'switch' },
    ],
    mockData: () => ({}),
  },

  borderBox: {
    type: 'borderBox',
    label: '边框容器',
    icon: '□',
    color: '#2563eb',
    category: 'decoration',
    description: '用于承载分组的发光边框',
    defaultSize: { w: 420, h: 300 },
    defaultStyle: { opacity: 1, borderRadius: 6, background: 'rgba(15,23,42,0.35)', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      borderColor: '#2563eb',
      borderWidth: 2,
      glowIntensity: 'medium',
      title: '数据总览',
      showTitle: true,
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'showTitle', label: '显示标题', type: 'switch' },
      { key: 'borderColor', label: '边框颜色', type: 'text' },
      { key: 'borderWidth', label: '边框宽度', type: 'number' },
      { key: 'glowIntensity', label: '发光强度', type: 'select', options: ['none', 'low', 'medium', 'high'] },
    ],
    mockData: () => ({ title: '数据总览' }),
  },

  decoration: {
    type: 'decoration',
    label: '装饰线',
    icon: '━',
    color: '#f59e0b',
    category: 'decoration',
    description: '角标、线条、圆环等装饰元素',
    defaultSize: { w: 220, h: 160 },
    defaultStyle: { opacity: 1, borderRadius: 0, background: 'transparent', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      decoType: 'corner',
      color: '#2563eb',
      size: 26,
      lineWidth: 2,
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'decoType', label: '装饰类型', type: 'select', options: ['corner', 'lines', 'dots', 'circles', 'diamond'] },
      { key: 'color', label: '颜色', type: 'text' },
      { key: 'size', label: '尺寸', type: 'number' },
      { key: 'lineWidth', label: '线宽', type: 'number' },
    ],
    mockData: () => ({}),
  },

  background: {
    type: 'background',
    label: '背景层',
    icon: '▣',
    color: '#0f172a',
    category: 'decoration',
    description: '全屏背景色、渐变与网格',
    defaultSize: { w: 1920, h: 1080 },
    defaultStyle: { opacity: 1, borderRadius: 0, background: 'transparent', border: 'none', boxShadow: 'none' },
    defaultConfig: {
      bgType: 'gradient',
      color1: '#08111f',
      color2: '#102a43',
      gradientDirection: 'to bottom',
      showGrid: true,
      gridColor: 'rgba(56,189,248,0.07)',
      dataSource: { ...DEFAULT_DATA_SOURCE },
    },
    configFields: [
      { key: 'bgType', label: '背景类型', type: 'select', options: ['gradient', 'solid', 'image'] },
      { key: 'color1', label: '颜色1', type: 'text' },
      { key: 'color2', label: '颜色2', type: 'text' },
      { key: 'gradientDirection', label: '渐变方向', type: 'select', options: ['to bottom', 'to right', 'to bottom right', 'to top'] },
      { key: 'showGrid', label: '显示网格', type: 'switch' },
      { key: 'gridColor', label: '网格颜色', type: 'text' },
    ],
    mockData: () => ({}),
  },
}

export function getChartTypeConfig(type) {
  return CHART_TYPE_CONFIG[type] || null
}

export function getDefaultChartData(type) {
  const config = CHART_TYPE_CONFIG[type]
  if (!config) return {}

  const mockData = config.mockData ? config.mockData() : {}

  return {
    type: config.type,
    label: config.label,
    icon: config.icon,
    color: config.color,
    description: config.description,
    size: { ...config.defaultSize },
    style: { ...config.defaultStyle },
    config: { ...config.defaultConfig, ...mockData },
  }
}
